### PR TITLE
2.6.11

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
That's odd.

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by saraedum** [comment]
@isuruf, the problem on Windows is still there:
```
Traceback (most recent call last):
  File "C:\Miniconda\lib\shutil.py", line 544, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:\\bld\\tmpza3p83nr\\nauty26r11\\This_is_nauty26r11.' -> 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmppjju7fyw\\This_is_nauty26r11.'
```

**Comment by saraedum** [comment]
@isuruf: I'll notify upstream. Can we just repackage nauty and upload it here as a release blob on the repo? I like that better than all this `bld.bat` magic that you built :)

**Comment by saraedum** [comment]
[nauty26r11.tar.gz](https://github.com/conda-forge/nauty-feedstock/files/3713871/nauty26r11.tar.gz)

Here's the tarball after a `tar --delete` for that funny file.

**Comment by saraedum** [comment]
(We should probably put that file somewhere else but let's see first what happens.)

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
