### PR TITLE
Copy all header files 

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
I need the header files for https://github.com/conda-forge/staged-recipes/pull/10403

**Comment by isuruf** [comment]
Not sure why drone is not shown

**Comment by isuruf** [comment]
Looks good to me. Can you add a test for the header you need?

**Comment by jan-janssen** [comment]
> Not sure why drone is not shown

It just took a little longer, now it appeared. @isuruf Can you merge the pull request?

**Comment by jan-janssen** [comment]
@isuruf I added the tests and all checks completed successful. Can you merge this pull request?

**Pull request merged**
